/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityItem
 */
export interface ActivityItem {
    /**
     * 
     * @type {string}
     * @memberof ActivityItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityItem
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityItem
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof ActivityItem
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityItem
     */
    meta?: string | null;
}

/**
 * Check if a given object implements the ActivityItem interface.
 */
export function instanceOfActivityItem(value: object): value is ActivityItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ActivityItemFromJSON(json: any): ActivityItem {
    return ActivityItemFromJSONTyped(json, false);
}

export function ActivityItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'description': json['description'],
        'timestamp': json['timestamp'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function ActivityItemToJSON(json: any): ActivityItem {
    return ActivityItemToJSONTyped(json, false);
}

export function ActivityItemToJSONTyped(value?: ActivityItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'description': value['description'],
        'timestamp': value['timestamp'],
        'meta': value['meta'],
    };
}

