/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentThought
 */
export interface AgentThought {
    /**
     * 
     * @type {string}
     * @memberof AgentThought
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AgentThought
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof AgentThought
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof AgentThought
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof AgentThought
     */
    timestamp: number;
}

/**
 * Check if a given object implements the AgentThought interface.
 */
export function instanceOfAgentThought(value: object): value is AgentThought {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AgentThoughtFromJSON(json: any): AgentThought {
    return AgentThoughtFromJSONTyped(json, false);
}

export function AgentThoughtFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentThought {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'content': json['content'],
        'status': json['status'],
        'timestamp': json['timestamp'],
    };
}

export function AgentThoughtToJSON(json: any): AgentThought {
    return AgentThoughtToJSONTyped(json, false);
}

export function AgentThoughtToJSONTyped(value?: AgentThought | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'status': value['status'],
        'timestamp': value['timestamp'],
    };
}

