/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyPayload
 */
export interface ApiKeyPayload {
    /**
     * 
     * @type {string}
     * @memberof ApiKeyPayload
     */
    openai?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyPayload
     */
    anthropic?: string | null;
}

/**
 * Check if a given object implements the ApiKeyPayload interface.
 */
export function instanceOfApiKeyPayload(value: object): value is ApiKeyPayload {
    return true;
}

export function ApiKeyPayloadFromJSON(json: any): ApiKeyPayload {
    return ApiKeyPayloadFromJSONTyped(json, false);
}

export function ApiKeyPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'openai': json['openai'] == null ? undefined : json['openai'],
        'anthropic': json['anthropic'] == null ? undefined : json['anthropic'],
    };
}

export function ApiKeyPayloadToJSON(json: any): ApiKeyPayload {
    return ApiKeyPayloadToJSONTyped(json, false);
}

export function ApiKeyPayloadToJSONTyped(value?: ApiKeyPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'openai': value['openai'],
        'anthropic': value['anthropic'],
    };
}

