/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeySummary
 */
export interface ApiKeySummary {
    /**
     * 
     * @type {string}
     * @memberof ApiKeySummary
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeySummary
     */
    last4: string;
    /**
     * 
     * @type {number}
     * @memberof ApiKeySummary
     */
    storedAt: number;
}

/**
 * Check if a given object implements the ApiKeySummary interface.
 */
export function instanceOfApiKeySummary(value: object): value is ApiKeySummary {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('last4' in value) || value['last4'] === undefined) return false;
    if (!('storedAt' in value) || value['storedAt'] === undefined) return false;
    return true;
}

export function ApiKeySummaryFromJSON(json: any): ApiKeySummary {
    return ApiKeySummaryFromJSONTyped(json, false);
}

export function ApiKeySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'last4': json['last4'],
        'storedAt': json['storedAt'],
    };
}

export function ApiKeySummaryToJSON(json: any): ApiKeySummary {
    return ApiKeySummaryToJSONTyped(json, false);
}

export function ApiKeySummaryToJSONTyped(value?: ApiKeySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'last4': value['last4'],
        'storedAt': value['storedAt'],
    };
}

