/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKeySummary } from './ApiKeySummary';
import {
    ApiKeySummaryFromJSON,
    ApiKeySummaryFromJSONTyped,
    ApiKeySummaryToJSON,
    ApiKeySummaryToJSONTyped,
} from './ApiKeySummary';

/**
 * 
 * @export
 * @interface ApiKeysResponse
 */
export interface ApiKeysResponse {
    /**
     * 
     * @type {Array<ApiKeySummary>}
     * @memberof ApiKeysResponse
     */
    keys: Array<ApiKeySummary>;
}

/**
 * Check if a given object implements the ApiKeysResponse interface.
 */
export function instanceOfApiKeysResponse(value: object): value is ApiKeysResponse {
    if (!('keys' in value) || value['keys'] === undefined) return false;
    return true;
}

export function ApiKeysResponseFromJSON(json: any): ApiKeysResponse {
    return ApiKeysResponseFromJSONTyped(json, false);
}

export function ApiKeysResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeysResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': ((json['keys'] as Array<any>).map(ApiKeySummaryFromJSON)),
    };
}

export function ApiKeysResponseToJSON(json: any): ApiKeysResponse {
    return ApiKeysResponseToJSONTyped(json, false);
}

export function ApiKeysResponseToJSONTyped(value?: ApiKeysResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keys': ((value['keys'] as Array<any>).map(ApiKeySummaryToJSON)),
    };
}

