/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentThought } from './AgentThought';
import {
    AgentThoughtFromJSON,
    AgentThoughtFromJSONTyped,
    AgentThoughtToJSON,
    AgentThoughtToJSONTyped,
} from './AgentThought';

/**
 * 
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    senderId: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    senderType: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    content: string;
    /**
     * 
     * @type {Array<AgentThought>}
     * @memberof ChatMessage
     */
    thoughts?: Array<AgentThought> | null;
    /**
     * 
     * @type {number}
     * @memberof ChatMessage
     */
    timestamp: number;
}

/**
 * Check if a given object implements the ChatMessage interface.
 */
export function instanceOfChatMessage(value: object): value is ChatMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('senderId' in value) || value['senderId'] === undefined) return false;
    if (!('senderType' in value) || value['senderType'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ChatMessageFromJSON(json: any): ChatMessage {
    return ChatMessageFromJSONTyped(json, false);
}

export function ChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['projectId'],
        'senderId': json['senderId'],
        'senderType': json['senderType'],
        'content': json['content'],
        'thoughts': json['thoughts'] == null ? undefined : ((json['thoughts'] as Array<any>).map(AgentThoughtFromJSON)),
        'timestamp': json['timestamp'],
    };
}

export function ChatMessageToJSON(json: any): ChatMessage {
    return ChatMessageToJSONTyped(json, false);
}

export function ChatMessageToJSONTyped(value?: ChatMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'senderId': value['senderId'],
        'senderType': value['senderType'],
        'content': value['content'],
        'thoughts': value['thoughts'] == null ? undefined : ((value['thoughts'] as Array<any>).map(AgentThoughtToJSON)),
        'timestamp': value['timestamp'],
    };
}

