/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteAccountRequest
 */
export interface DeleteAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof DeleteAccountRequest
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeleteAccountRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeleteAccountRequest
     */
    supabaseUserId?: string | null;
}

/**
 * Check if a given object implements the DeleteAccountRequest interface.
 */
export function instanceOfDeleteAccountRequest(value: object): value is DeleteAccountRequest {
    return true;
}

export function DeleteAccountRequestFromJSON(json: any): DeleteAccountRequest {
    return DeleteAccountRequestFromJSONTyped(json, false);
}

export function DeleteAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'email': json['email'] == null ? undefined : json['email'],
        'supabaseUserId': json['supabaseUserId'] == null ? undefined : json['supabaseUserId'],
    };
}

export function DeleteAccountRequestToJSON(json: any): DeleteAccountRequest {
    return DeleteAccountRequestToJSONTyped(json, false);
}

export function DeleteAccountRequestToJSONTyped(value?: DeleteAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'email': value['email'],
        'supabaseUserId': value['supabaseUserId'],
    };
}

