/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceRevokeResponse
 */
export interface DeviceRevokeResponse {
    /**
     * Number of device records marked revoked
     * @type {number}
     * @memberof DeviceRevokeResponse
     */
    revoked: number;
    /**
     * Number of refresh tokens invalidated via auth admin
     * @type {number}
     * @memberof DeviceRevokeResponse
     */
    tokensRevoked: number;
}

/**
 * Check if a given object implements the DeviceRevokeResponse interface.
 */
export function instanceOfDeviceRevokeResponse(value: object): value is DeviceRevokeResponse {
    if (!('revoked' in value) || value['revoked'] === undefined) return false;
    if (!('tokensRevoked' in value) || value['tokensRevoked'] === undefined) return false;
    return true;
}

export function DeviceRevokeResponseFromJSON(json: any): DeviceRevokeResponse {
    return DeviceRevokeResponseFromJSONTyped(json, false);
}

export function DeviceRevokeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceRevokeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'revoked': json['revoked'],
        'tokensRevoked': json['tokensRevoked'],
    };
}

export function DeviceRevokeResponseToJSON(json: any): DeviceRevokeResponse {
    return DeviceRevokeResponseToJSONTyped(json, false);
}

export function DeviceRevokeResponseToJSONTyped(value?: DeviceRevokeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'revoked': value['revoked'],
        'tokensRevoked': value['tokensRevoked'],
    };
}

