/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceDeleteResponse
 */
export interface DeviceDeleteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DeviceDeleteResponse
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the DeviceDeleteResponse interface.
 */
export function instanceOfDeviceDeleteResponse(value: object): value is DeviceDeleteResponse {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function DeviceDeleteResponseFromJSON(json: any): DeviceDeleteResponse {
    return DeviceDeleteResponseFromJSONTyped(json, false);
}

export function DeviceDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
    };
}

export function DeviceDeleteResponseToJSON(json: any): DeviceDeleteResponse {
    return DeviceDeleteResponseToJSONTyped(json, false);
}

export function DeviceDeleteResponseToJSONTyped(value?: DeviceDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

