/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceRecord } from './DeviceRecord';
import {
    DeviceRecordFromJSON,
    DeviceRecordFromJSONTyped,
    DeviceRecordToJSON,
    DeviceRecordToJSONTyped,
} from './DeviceRecord';

/**
 * 
 * @export
 * @interface DeviceListResponse
 */
export interface DeviceListResponse {
    /**
     * 
     * @type {Array<DeviceRecord>}
     * @memberof DeviceListResponse
     */
    devices: Array<DeviceRecord>;
}

/**
 * Check if a given object implements the DeviceListResponse interface.
 */
export function instanceOfDeviceListResponse(value: object): value is DeviceListResponse {
    if (!('devices' in value) || value['devices'] === undefined) return false;
    return true;
}

export function DeviceListResponseFromJSON(json: any): DeviceListResponse {
    return DeviceListResponseFromJSONTyped(json, false);
}

export function DeviceListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'devices': ((json['devices'] as Array<any>).map(DeviceRecordFromJSON)),
    };
}

export function DeviceListResponseToJSON(json: any): DeviceListResponse {
    return DeviceListResponseToJSONTyped(json, false);
}

export function DeviceListResponseToJSONTyped(value?: DeviceListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'devices': ((value['devices'] as Array<any>).map(DeviceRecordToJSON)),
    };
}

