/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceUpsertRequest
 */
export interface DeviceUpsertRequest {
    /**
     * Client-generated stable device identifier
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    deviceId: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    userAgent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    platform?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    browser?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    os?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    timezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    locale?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    screen?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DeviceUpsertRequest
     */
    deviceMemory?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    region?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    ip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    label?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceUpsertRequest
     */
    isTrusted?: boolean | null;
    /**
     * Whether this event is a login (updates last_login_at)
     * @type {boolean}
     * @memberof DeviceUpsertRequest
     */
    login?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeviceUpsertRequest
     */
    refreshToken?: string | null;
}

/**
 * Check if a given object implements the DeviceUpsertRequest interface.
 */
export function instanceOfDeviceUpsertRequest(value: object): value is DeviceUpsertRequest {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    return true;
}

export function DeviceUpsertRequestFromJSON(json: any): DeviceUpsertRequest {
    return DeviceUpsertRequestFromJSONTyped(json, false);
}

export function DeviceUpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceUpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['deviceId'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'browser': json['browser'] == null ? undefined : json['browser'],
        'os': json['os'] == null ? undefined : json['os'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'screen': json['screen'] == null ? undefined : json['screen'],
        'deviceMemory': json['deviceMemory'] == null ? undefined : json['deviceMemory'],
        'city': json['city'] == null ? undefined : json['city'],
        'region': json['region'] == null ? undefined : json['region'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'label': json['label'] == null ? undefined : json['label'],
        'isTrusted': json['isTrusted'] == null ? undefined : json['isTrusted'],
        'login': json['login'] == null ? undefined : json['login'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function DeviceUpsertRequestToJSON(json: any): DeviceUpsertRequest {
    return DeviceUpsertRequestToJSONTyped(json, false);
}

export function DeviceUpsertRequestToJSONTyped(value?: DeviceUpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceId': value['deviceId'],
        'userAgent': value['userAgent'],
        'platform': value['platform'],
        'browser': value['browser'],
        'os': value['os'],
        'timezone': value['timezone'],
        'locale': value['locale'],
        'screen': value['screen'],
        'deviceMemory': value['deviceMemory'],
        'city': value['city'],
        'region': value['region'],
        'ip': value['ip'],
        'label': value['label'],
        'isTrusted': value['isTrusted'],
        'login': value['login'],
        'refreshToken': value['refreshToken'],
    };
}

