/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceRecord
 */
export interface DeviceRecord {
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    deviceId: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    userAgent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    platform?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    browser?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    os?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    timezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    locale?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    screen?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DeviceRecord
     */
    deviceMemory?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    region?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    ip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceRecord
     */
    label?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceRecord
     */
    isTrusted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DeviceRecord
     */
    firstSeenAt: number;
    /**
     * 
     * @type {number}
     * @memberof DeviceRecord
     */
    lastSeenAt: number;
    /**
     * 
     * @type {number}
     * @memberof DeviceRecord
     */
    lastLoginAt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DeviceRecord
     */
    revokedAt?: number | null;
}

/**
 * Check if a given object implements the DeviceRecord interface.
 */
export function instanceOfDeviceRecord(value: object): value is DeviceRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('firstSeenAt' in value) || value['firstSeenAt'] === undefined) return false;
    if (!('lastSeenAt' in value) || value['lastSeenAt'] === undefined) return false;
    return true;
}

export function DeviceRecordFromJSON(json: any): DeviceRecord {
    return DeviceRecordFromJSONTyped(json, false);
}

export function DeviceRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'deviceId': json['deviceId'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'browser': json['browser'] == null ? undefined : json['browser'],
        'os': json['os'] == null ? undefined : json['os'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'screen': json['screen'] == null ? undefined : json['screen'],
        'deviceMemory': json['deviceMemory'] == null ? undefined : json['deviceMemory'],
        'city': json['city'] == null ? undefined : json['city'],
        'region': json['region'] == null ? undefined : json['region'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'label': json['label'] == null ? undefined : json['label'],
        'isTrusted': json['isTrusted'] == null ? undefined : json['isTrusted'],
        'firstSeenAt': json['firstSeenAt'],
        'lastSeenAt': json['lastSeenAt'],
        'lastLoginAt': json['lastLoginAt'] == null ? undefined : json['lastLoginAt'],
        'revokedAt': json['revokedAt'] == null ? undefined : json['revokedAt'],
    };
}

export function DeviceRecordToJSON(json: any): DeviceRecord {
    return DeviceRecordToJSONTyped(json, false);
}

export function DeviceRecordToJSONTyped(value?: DeviceRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'deviceId': value['deviceId'],
        'userAgent': value['userAgent'],
        'platform': value['platform'],
        'browser': value['browser'],
        'os': value['os'],
        'timezone': value['timezone'],
        'locale': value['locale'],
        'screen': value['screen'],
        'deviceMemory': value['deviceMemory'],
        'city': value['city'],
        'region': value['region'],
        'ip': value['ip'],
        'label': value['label'],
        'isTrusted': value['isTrusted'],
        'firstSeenAt': value['firstSeenAt'],
        'lastSeenAt': value['lastSeenAt'],
        'lastLoginAt': value['lastLoginAt'],
        'revokedAt': value['revokedAt'],
    };
}

