/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceRevokeRequest
 */
export interface DeviceRevokeRequest {
    /**
     * Revoke a specific device, all except the caller, or all devices
     * @type {string}
     * @memberof DeviceRevokeRequest
     */
    scope?: DeviceRevokeRequestScopeEnum;
    /**
     * 
     * @type {string}
     * @memberof DeviceRevokeRequest
     */
    deviceId?: string | null;
}


/**
 * @export
 */
export const DeviceRevokeRequestScopeEnum = {
    Single: 'single',
    Others: 'others',
    All: 'all'
} as const;
export type DeviceRevokeRequestScopeEnum = typeof DeviceRevokeRequestScopeEnum[keyof typeof DeviceRevokeRequestScopeEnum];


/**
 * Check if a given object implements the DeviceRevokeRequest interface.
 */
export function instanceOfDeviceRevokeRequest(value: object): value is DeviceRevokeRequest {
    return true;
}

export function DeviceRevokeRequestFromJSON(json: any): DeviceRevokeRequest {
    return DeviceRevokeRequestFromJSONTyped(json, false);
}

export function DeviceRevokeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceRevokeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'] == null ? undefined : json['scope'],
        'deviceId': json['deviceId'] == null ? undefined : json['deviceId'],
    };
}

export function DeviceRevokeRequestToJSON(json: any): DeviceRevokeRequest {
    return DeviceRevokeRequestToJSONTyped(json, false);
}

export function DeviceRevokeRequestToJSONTyped(value?: DeviceRevokeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'deviceId': value['deviceId'],
    };
}

