/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Preferences
 */
export interface Preferences {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    theme?: string;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    organization?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    bio?: string | null;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: any; }; }}
     * @memberof Preferences
     */
    apiKeys?: { [key: string]: { [key: string]: any; }; } | null;
}

/**
 * Check if a given object implements the Preferences interface.
 */
export function instanceOfPreferences(value: object): value is Preferences {
    return true;
}

export function PreferencesFromJSON(json: any): Preferences {
    return PreferencesFromJSONTyped(json, false);
}

export function PreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preferences {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'theme': json['theme'] == null ? undefined : json['theme'],
        'title': json['title'] == null ? undefined : json['title'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'location': json['location'] == null ? undefined : json['location'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'apiKeys': json['apiKeys'] == null ? undefined : json['apiKeys'],
    };
}

export function PreferencesToJSON(json: any): Preferences {
    return PreferencesToJSONTyped(json, false);
}

export function PreferencesToJSONTyped(value?: Preferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'theme': value['theme'],
        'title': value['title'],
        'organization': value['organization'],
        'location': value['location'],
        'bio': value['bio'],
        'apiKeys': value['apiKeys'],
    };
}

