/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectShare
 */
export interface ProjectShare {
    /**
     * 
     * @type {string}
     * @memberof ProjectShare
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectShare
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectShare
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectShare
     */
    access: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectShare
     */
    invitedAt: number;
}

/**
 * Check if a given object implements the ProjectShare interface.
 */
export function instanceOfProjectShare(value: object): value is ProjectShare {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('access' in value) || value['access'] === undefined) return false;
    if (!('invitedAt' in value) || value['invitedAt'] === undefined) return false;
    return true;
}

export function ProjectShareFromJSON(json: any): ProjectShare {
    return ProjectShareFromJSONTyped(json, false);
}

export function ProjectShareFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectShare {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['projectId'],
        'email': json['email'],
        'access': json['access'],
        'invitedAt': json['invitedAt'],
    };
}

export function ProjectShareToJSON(json: any): ProjectShare {
    return ProjectShareToJSONTyped(json, false);
}

export function ProjectShareToJSONTyped(value?: ProjectShare | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'email': value['email'],
        'access': value['access'],
        'invitedAt': value['invitedAt'],
    };
}

