/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectStats
 */
export interface ProjectStats {
    /**
     * 
     * @type {number}
     * @memberof ProjectStats
     */
    totalProjects: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectStats
     */
    activeProjects: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectStats
     */
    completedProjects: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectStats
     */
    updatedLastDay: number;
}

/**
 * Check if a given object implements the ProjectStats interface.
 */
export function instanceOfProjectStats(value: object): value is ProjectStats {
    if (!('totalProjects' in value) || value['totalProjects'] === undefined) return false;
    if (!('activeProjects' in value) || value['activeProjects'] === undefined) return false;
    if (!('completedProjects' in value) || value['completedProjects'] === undefined) return false;
    if (!('updatedLastDay' in value) || value['updatedLastDay'] === undefined) return false;
    return true;
}

export function ProjectStatsFromJSON(json: any): ProjectStats {
    return ProjectStatsFromJSONTyped(json, false);
}

export function ProjectStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectStats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalProjects': json['totalProjects'],
        'activeProjects': json['activeProjects'],
        'completedProjects': json['completedProjects'],
        'updatedLastDay': json['updatedLastDay'],
    };
}

export function ProjectStatsToJSON(json: any): ProjectStats {
    return ProjectStatsToJSONTyped(json, false);
}

export function ProjectStatsToJSONTyped(value?: ProjectStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalProjects': value['totalProjects'],
        'activeProjects': value['activeProjects'],
        'completedProjects': value['completedProjects'],
        'updatedLastDay': value['updatedLastDay'],
    };
}

