/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResearchProject
 */
export interface ResearchProject {
    /**
     * 
     * @type {string}
     * @memberof ResearchProject
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResearchProject
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ResearchProject
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ResearchProject
     */
    goal: string;
    /**
     * 
     * @type {string}
     * @memberof ResearchProject
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof ResearchProject
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof ResearchProject
     */
    updatedAt: number;
    /**
     * 
     * @type {number}
     * @memberof ResearchProject
     */
    lastMessageAt?: number | null;
}

/**
 * Check if a given object implements the ResearchProject interface.
 */
export function instanceOfResearchProject(value: object): value is ResearchProject {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('goal' in value) || value['goal'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ResearchProjectFromJSON(json: any): ResearchProject {
    return ResearchProjectFromJSONTyped(json, false);
}

export function ResearchProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchProject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'title': json['title'],
        'goal': json['goal'],
        'status': json['status'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'lastMessageAt': json['lastMessageAt'] == null ? undefined : json['lastMessageAt'],
    };
}

export function ResearchProjectToJSON(json: any): ResearchProject {
    return ResearchProjectToJSONTyped(json, false);
}

export function ResearchProjectToJSONTyped(value?: ResearchProject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'title': value['title'],
        'goal': value['goal'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'lastMessageAt': value['lastMessageAt'],
    };
}

