/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResearchPlanItem
 */
export interface ResearchPlanItem {
    /**
     * 
     * @type {string}
     * @memberof ResearchPlanItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResearchPlanItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ResearchPlanItem
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ResearchPlanItem
     */
    status: string;
    /**
     * 
     * @type {Array<ResearchPlanItem>}
     * @memberof ResearchPlanItem
     */
    subItems?: Array<ResearchPlanItem> | null;
}

/**
 * Check if a given object implements the ResearchPlanItem interface.
 */
export function instanceOfResearchPlanItem(value: object): value is ResearchPlanItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ResearchPlanItemFromJSON(json: any): ResearchPlanItem {
    return ResearchPlanItemFromJSONTyped(json, false);
}

export function ResearchPlanItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchPlanItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'status': json['status'],
        'subItems': json['subItems'] == null ? undefined : ((json['subItems'] as Array<any>).map(ResearchPlanItemFromJSON)),
    };
}

export function ResearchPlanItemToJSON(json: any): ResearchPlanItem {
    return ResearchPlanItemToJSONTyped(json, false);
}

export function ResearchPlanItemToJSONTyped(value?: ResearchPlanItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'status': value['status'],
        'subItems': value['subItems'] == null ? undefined : ((value['subItems'] as Array<any>).map(ResearchPlanItemToJSON)),
    };
}

