/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResearchPlanItem } from './ResearchPlanItem';
import {
    ResearchPlanItemFromJSON,
    ResearchPlanItemFromJSONTyped,
    ResearchPlanItemToJSON,
    ResearchPlanItemToJSONTyped,
} from './ResearchPlanItem';

/**
 * 
 * @export
 * @interface ResearchPlan
 */
export interface ResearchPlan {
    /**
     * 
     * @type {string}
     * @memberof ResearchPlan
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResearchPlan
     */
    projectId: string;
    /**
     * 
     * @type {Array<ResearchPlanItem>}
     * @memberof ResearchPlan
     */
    items: Array<ResearchPlanItem>;
    /**
     * 
     * @type {number}
     * @memberof ResearchPlan
     */
    updatedAt: number;
}

/**
 * Check if a given object implements the ResearchPlan interface.
 */
export function instanceOfResearchPlan(value: object): value is ResearchPlan {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ResearchPlanFromJSON(json: any): ResearchPlan {
    return ResearchPlanFromJSONTyped(json, false);
}

export function ResearchPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['projectId'],
        'items': ((json['items'] as Array<any>).map(ResearchPlanItemFromJSON)),
        'updatedAt': json['updatedAt'],
    };
}

export function ResearchPlanToJSON(json: any): ResearchPlan {
    return ResearchPlanToJSONTyped(json, false);
}

export function ResearchPlanToJSONTyped(value?: ResearchPlan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'items': ((value['items'] as Array<any>).map(ResearchPlanItemToJSON)),
        'updatedAt': value['updatedAt'],
    };
}

