/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResearchPlan } from './ResearchPlan';
import {
    ResearchPlanFromJSON,
    ResearchPlanFromJSONTyped,
    ResearchPlanToJSON,
    ResearchPlanToJSONTyped,
} from './ResearchPlan';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';

/**
 * 
 * @export
 * @interface SendMessageResponse
 */
export interface SendMessageResponse {
    /**
     * 
     * @type {ChatMessage}
     * @memberof SendMessageResponse
     */
    userMessage: ChatMessage;
    /**
     * 
     * @type {ChatMessage}
     * @memberof SendMessageResponse
     */
    agentMessage: ChatMessage;
    /**
     * 
     * @type {ResearchPlan}
     * @memberof SendMessageResponse
     */
    plan?: ResearchPlan | null;
}

/**
 * Check if a given object implements the SendMessageResponse interface.
 */
export function instanceOfSendMessageResponse(value: object): value is SendMessageResponse {
    if (!('userMessage' in value) || value['userMessage'] === undefined) return false;
    if (!('agentMessage' in value) || value['agentMessage'] === undefined) return false;
    return true;
}

export function SendMessageResponseFromJSON(json: any): SendMessageResponse {
    return SendMessageResponseFromJSONTyped(json, false);
}

export function SendMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userMessage': ChatMessageFromJSON(json['userMessage']),
        'agentMessage': ChatMessageFromJSON(json['agentMessage']),
        'plan': json['plan'] == null ? undefined : ResearchPlanFromJSON(json['plan']),
    };
}

export function SendMessageResponseToJSON(json: any): SendMessageResponse {
    return SendMessageResponseToJSONTyped(json, false);
}

export function SendMessageResponseToJSONTyped(value?: SendMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userMessage': ChatMessageToJSON(value['userMessage']),
        'agentMessage': ChatMessageToJSON(value['agentMessage']),
        'plan': ResearchPlanToJSON(value['plan']),
    };
}

