/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareProjectRequest
 */
export interface ShareProjectRequest {
    /**
     * Email to share the project with
     * @type {string}
     * @memberof ShareProjectRequest
     */
    email: string;
    /**
     * viewer | editor
     * @type {string}
     * @memberof ShareProjectRequest
     */
    access?: string;
}

/**
 * Check if a given object implements the ShareProjectRequest interface.
 */
export function instanceOfShareProjectRequest(value: object): value is ShareProjectRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ShareProjectRequestFromJSON(json: any): ShareProjectRequest {
    return ShareProjectRequestFromJSONTyped(json, false);
}

export function ShareProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'access': json['access'] == null ? undefined : json['access'],
    };
}

export function ShareProjectRequestToJSON(json: any): ShareProjectRequest {
    return ShareProjectRequestToJSONTyped(json, false);
}

export function ShareProjectRequestToJSONTyped(value?: ShareProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'access': value['access'],
    };
}

