/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteAccountRequest,
  DeviceDeleteResponse,
  DeviceListResponse,
  DeviceRecord,
  DeviceRevokeRequest,
  DeviceRevokeResponse,
  DeviceUpsertRequest,
  HTTPValidationError,
  LoginRequest,
  User,
} from '../models/index';
import {
    DeleteAccountRequestFromJSON,
    DeleteAccountRequestToJSON,
    DeviceDeleteResponseFromJSON,
    DeviceDeleteResponseToJSON,
    DeviceListResponseFromJSON,
    DeviceListResponseToJSON,
    DeviceRecordFromJSON,
    DeviceRecordToJSON,
    DeviceRevokeRequestFromJSON,
    DeviceRevokeRequestToJSON,
    DeviceRevokeResponseFromJSON,
    DeviceRevokeResponseToJSON,
    DeviceUpsertRequestFromJSON,
    DeviceUpsertRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface CurrentUserAuthMeGetRequest {
    email?: string | null;
    userId?: string | null;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface DeleteAccountAuthAccountDeleteRequest {
    deleteAccountRequest: DeleteAccountRequest;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface DeleteDeviceAuthDevicesDeviceIdDeleteRequest {
    deviceId: string;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface ListDevicesAuthDevicesGetRequest {
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface LoginAuthLoginPostRequest {
    loginRequest: LoginRequest;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface RevokeDevicesAuthDevicesRevokePostRequest {
    deviceRevokeRequest: DeviceRevokeRequest;
    xDeviceId?: string | null;
    authorization?: string | null;
}

export interface UpsertDeviceAuthDevicesPostRequest {
    deviceUpsertRequest: DeviceUpsertRequest;
    xDeviceId?: string | null;
    authorization?: string | null;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Current User
     */
    async currentUserAuthMeGetRaw(requestParameters: CurrentUserAuthMeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const queryParameters: any = {};

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Current User
     */
    async currentUserAuthMeGet(requestParameters: CurrentUserAuthMeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.currentUserAuthMeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Account
     */
    async deleteAccountAuthAccountDeleteRaw(requestParameters: DeleteAccountAuthAccountDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['deleteAccountRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteAccountRequest',
                'Required parameter "deleteAccountRequest" was null or undefined when calling deleteAccountAuthAccountDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/auth/account`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteAccountRequestToJSON(requestParameters['deleteAccountRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Account
     */
    async deleteAccountAuthAccountDelete(requestParameters: DeleteAccountAuthAccountDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteAccountAuthAccountDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Device
     */
    async deleteDeviceAuthDevicesDeviceIdDeleteRaw(requestParameters: DeleteDeviceAuthDevicesDeviceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceDeleteResponse>> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling deleteDeviceAuthDevicesDeviceIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/auth/devices/{deviceId}`;
        urlPath = urlPath.replace(`{${"deviceId"}}`, encodeURIComponent(String(requestParameters['deviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceDeleteResponseFromJSON(jsonValue));
    }

    /**
     * Delete Device
     */
    async deleteDeviceAuthDevicesDeviceIdDelete(requestParameters: DeleteDeviceAuthDevicesDeviceIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceDeleteResponse> {
        const response = await this.deleteDeviceAuthDevicesDeviceIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Devices
     */
    async listDevicesAuthDevicesGetRaw(requestParameters: ListDevicesAuthDevicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/auth/devices`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceListResponseFromJSON(jsonValue));
    }

    /**
     * List Devices
     */
    async listDevicesAuthDevicesGet(requestParameters: ListDevicesAuthDevicesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceListResponse> {
        const response = await this.listDevicesAuthDevicesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Login
     */
    async loginAuthLoginPostRaw(requestParameters: LoginAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling loginAuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Login
     */
    async loginAuthLoginPost(requestParameters: LoginAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.loginAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke Devices
     */
    async revokeDevicesAuthDevicesRevokePostRaw(requestParameters: RevokeDevicesAuthDevicesRevokePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceRevokeResponse>> {
        if (requestParameters['deviceRevokeRequest'] == null) {
            throw new runtime.RequiredError(
                'deviceRevokeRequest',
                'Required parameter "deviceRevokeRequest" was null or undefined when calling revokeDevicesAuthDevicesRevokePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/auth/devices/revoke`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeviceRevokeRequestToJSON(requestParameters['deviceRevokeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceRevokeResponseFromJSON(jsonValue));
    }

    /**
     * Revoke Devices
     */
    async revokeDevicesAuthDevicesRevokePost(requestParameters: RevokeDevicesAuthDevicesRevokePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceRevokeResponse> {
        const response = await this.revokeDevicesAuthDevicesRevokePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upsert Device
     */
    async upsertDeviceAuthDevicesPostRaw(requestParameters: UpsertDeviceAuthDevicesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceRecord>> {
        if (requestParameters['deviceUpsertRequest'] == null) {
            throw new runtime.RequiredError(
                'deviceUpsertRequest',
                'Required parameter "deviceUpsertRequest" was null or undefined when calling upsertDeviceAuthDevicesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/auth/devices`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeviceUpsertRequestToJSON(requestParameters['deviceUpsertRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceRecordFromJSON(jsonValue));
    }

    /**
     * Upsert Device
     */
    async upsertDeviceAuthDevicesPost(requestParameters: UpsertDeviceAuthDevicesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceRecord> {
        const response = await this.upsertDeviceAuthDevicesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
