/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ActivityItem,
  ChatMessage,
  CreateMessageRequest,
  CreateProjectRequest,
  HTTPValidationError,
  ProjectShare,
  ProjectStats,
  ResearchPlan,
  ResearchProject,
  SendMessageResponse,
  ShareProjectRequest,
  UpdateProjectRequest,
} from '../models/index';
import {
    ActivityItemFromJSON,
    ActivityItemToJSON,
    ChatMessageFromJSON,
    ChatMessageToJSON,
    CreateMessageRequestFromJSON,
    CreateMessageRequestToJSON,
    CreateProjectRequestFromJSON,
    CreateProjectRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ProjectShareFromJSON,
    ProjectShareToJSON,
    ProjectStatsFromJSON,
    ProjectStatsToJSON,
    ResearchPlanFromJSON,
    ResearchPlanToJSON,
    ResearchProjectFromJSON,
    ResearchProjectToJSON,
    SendMessageResponseFromJSON,
    SendMessageResponseToJSON,
    ShareProjectRequestFromJSON,
    ShareProjectRequestToJSON,
    UpdateProjectRequestFromJSON,
    UpdateProjectRequestToJSON,
} from '../models/index';

export interface CreateProjectProjectsPostRequest {
    createProjectRequest: CreateProjectRequest;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface DeleteProjectProjectsProjectIdDeleteRequest {
    projectId: string;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface GetMessagesProjectsProjectIdMessagesGetRequest {
    projectId: string;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface GetPlanProjectsProjectIdPlanGetRequest {
    projectId: string;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface GetProjectProjectsProjectIdGetRequest {
    projectId: string;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface ListProjectSharesProjectsProjectIdSharesGetRequest {
    projectId: string;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface ListProjectsProjectsGetRequest {
    userId: string;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface ProjectStatsProjectsStatsGetRequest {
    userId: string;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface RecentActivityProjectsActivityGetRequest {
    userId: string;
    limit?: number;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface RevokeProjectShareProjectsProjectIdSharesShareIdDeleteRequest {
    projectId: string;
    shareId: string;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface SendMessageProjectsProjectIdMessagesPostRequest {
    projectId: string;
    createMessageRequest: CreateMessageRequest;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface ShareProjectProjectsProjectIdSharesPostRequest {
    projectId: string;
    shareProjectRequest: ShareProjectRequest;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface UpdateProjectProjectsProjectIdPatchRequest {
    projectId: string;
    updateProjectRequest: UpdateProjectRequest;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

/**
 * 
 */
export class ProjectsApi extends runtime.BaseAPI {

    /**
     * Create Project
     */
    async createProjectProjectsPostRaw(requestParameters: CreateProjectProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResearchProject>> {
        if (requestParameters['createProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'createProjectRequest',
                'Required parameter "createProjectRequest" was null or undefined when calling createProjectProjectsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProjectRequestToJSON(requestParameters['createProjectRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResearchProjectFromJSON(jsonValue));
    }

    /**
     * Create Project
     */
    async createProjectProjectsPost(requestParameters: CreateProjectProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResearchProject> {
        const response = await this.createProjectProjectsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Project
     */
    async deleteProjectProjectsProjectIdDeleteRaw(requestParameters: DeleteProjectProjectsProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteProjectProjectsProjectIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Project
     */
    async deleteProjectProjectsProjectIdDelete(requestParameters: DeleteProjectProjectsProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProjectProjectsProjectIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Messages
     */
    async getMessagesProjectsProjectIdMessagesGetRaw(requestParameters: GetMessagesProjectsProjectIdMessagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChatMessage>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getMessagesProjectsProjectIdMessagesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/{project_id}/messages`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChatMessageFromJSON));
    }

    /**
     * Get Messages
     */
    async getMessagesProjectsProjectIdMessagesGet(requestParameters: GetMessagesProjectsProjectIdMessagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChatMessage>> {
        const response = await this.getMessagesProjectsProjectIdMessagesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Plan
     */
    async getPlanProjectsProjectIdPlanGetRaw(requestParameters: GetPlanProjectsProjectIdPlanGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResearchPlan>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getPlanProjectsProjectIdPlanGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/{project_id}/plan`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResearchPlanFromJSON(jsonValue));
    }

    /**
     * Get Plan
     */
    async getPlanProjectsProjectIdPlanGet(requestParameters: GetPlanProjectsProjectIdPlanGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResearchPlan> {
        const response = await this.getPlanProjectsProjectIdPlanGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Project
     */
    async getProjectProjectsProjectIdGetRaw(requestParameters: GetProjectProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResearchProject>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectProjectsProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResearchProjectFromJSON(jsonValue));
    }

    /**
     * Get Project
     */
    async getProjectProjectsProjectIdGet(requestParameters: GetProjectProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResearchProject> {
        const response = await this.getProjectProjectsProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Project Shares
     */
    async listProjectSharesProjectsProjectIdSharesGetRaw(requestParameters: ListProjectSharesProjectsProjectIdSharesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectShare>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listProjectSharesProjectsProjectIdSharesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/{project_id}/shares`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectShareFromJSON));
    }

    /**
     * List Project Shares
     */
    async listProjectSharesProjectsProjectIdSharesGet(requestParameters: ListProjectSharesProjectsProjectIdSharesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectShare>> {
        const response = await this.listProjectSharesProjectsProjectIdSharesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Projects
     */
    async listProjectsProjectsGetRaw(requestParameters: ListProjectsProjectsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ResearchProject>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listProjectsProjectsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ResearchProjectFromJSON));
    }

    /**
     * List Projects
     */
    async listProjectsProjectsGet(requestParameters: ListProjectsProjectsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ResearchProject>> {
        const response = await this.listProjectsProjectsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Project Stats
     */
    async projectStatsProjectsStatsGetRaw(requestParameters: ProjectStatsProjectsStatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectStats>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling projectStatsProjectsStatsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectStatsFromJSON(jsonValue));
    }

    /**
     * Project Stats
     */
    async projectStatsProjectsStatsGet(requestParameters: ProjectStatsProjectsStatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectStats> {
        const response = await this.projectStatsProjectsStatsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Recent Activity
     */
    async recentActivityProjectsActivityGetRaw(requestParameters: RecentActivityProjectsActivityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ActivityItem>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling recentActivityProjectsActivityGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/activity`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ActivityItemFromJSON));
    }

    /**
     * Recent Activity
     */
    async recentActivityProjectsActivityGet(requestParameters: RecentActivityProjectsActivityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ActivityItem>> {
        const response = await this.recentActivityProjectsActivityGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke Project Share
     */
    async revokeProjectShareProjectsProjectIdSharesShareIdDeleteRaw(requestParameters: RevokeProjectShareProjectsProjectIdSharesShareIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling revokeProjectShareProjectsProjectIdSharesShareIdDelete().'
            );
        }

        if (requestParameters['shareId'] == null) {
            throw new runtime.RequiredError(
                'shareId',
                'Required parameter "shareId" was null or undefined when calling revokeProjectShareProjectsProjectIdSharesShareIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/{project_id}/shares/{share_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"share_id"}}`, encodeURIComponent(String(requestParameters['shareId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke Project Share
     */
    async revokeProjectShareProjectsProjectIdSharesShareIdDelete(requestParameters: RevokeProjectShareProjectsProjectIdSharesShareIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeProjectShareProjectsProjectIdSharesShareIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Send Message
     */
    async sendMessageProjectsProjectIdMessagesPostRaw(requestParameters: SendMessageProjectsProjectIdMessagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendMessageResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling sendMessageProjectsProjectIdMessagesPost().'
            );
        }

        if (requestParameters['createMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'createMessageRequest',
                'Required parameter "createMessageRequest" was null or undefined when calling sendMessageProjectsProjectIdMessagesPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/{project_id}/messages`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMessageRequestToJSON(requestParameters['createMessageRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendMessageResponseFromJSON(jsonValue));
    }

    /**
     * Send Message
     */
    async sendMessageProjectsProjectIdMessagesPost(requestParameters: SendMessageProjectsProjectIdMessagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendMessageResponse> {
        const response = await this.sendMessageProjectsProjectIdMessagesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Share Project
     */
    async shareProjectProjectsProjectIdSharesPostRaw(requestParameters: ShareProjectProjectsProjectIdSharesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectShare>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling shareProjectProjectsProjectIdSharesPost().'
            );
        }

        if (requestParameters['shareProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'shareProjectRequest',
                'Required parameter "shareProjectRequest" was null or undefined when calling shareProjectProjectsProjectIdSharesPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/{project_id}/shares`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ShareProjectRequestToJSON(requestParameters['shareProjectRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectShareFromJSON(jsonValue));
    }

    /**
     * Share Project
     */
    async shareProjectProjectsProjectIdSharesPost(requestParameters: ShareProjectProjectsProjectIdSharesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectShare> {
        const response = await this.shareProjectProjectsProjectIdSharesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Project
     */
    async updateProjectProjectsProjectIdPatchRaw(requestParameters: UpdateProjectProjectsProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResearchProject>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectProjectsProjectIdPatch().'
            );
        }

        if (requestParameters['updateProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProjectRequest',
                'Required parameter "updateProjectRequest" was null or undefined when calling updateProjectProjectsProjectIdPatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProjectRequestToJSON(requestParameters['updateProjectRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResearchProjectFromJSON(jsonValue));
    }

    /**
     * Update Project
     */
    async updateProjectProjectsProjectIdPatch(requestParameters: UpdateProjectProjectsProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResearchProject> {
        const response = await this.updateProjectProjectsProjectIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
