/* tslint:disable */
/* eslint-disable */
/**
 * Intellex API
 * Backend for Intellex Research SaaS
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiKeyPayload,
  ApiKeysResponse,
  HTTPValidationError,
} from '../models/index';
import {
    ApiKeyPayloadFromJSON,
    ApiKeyPayloadToJSON,
    ApiKeysResponseFromJSON,
    ApiKeysResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetApiKeysUsersApiKeysGetRequest {
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

export interface SaveApiKeysUsersApiKeysPostRequest {
    apiKeyPayload: ApiKeyPayload;
    skipRevokedCheck?: boolean;
    authorization?: string | null;
    xDeviceId?: string | null;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Get Api Keys
     */
    async getApiKeysUsersApiKeysGetRaw(requestParameters: GetApiKeysUsersApiKeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeysResponse>> {
        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/users/api-keys`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeysResponseFromJSON(jsonValue));
    }

    /**
     * Get Api Keys
     */
    async getApiKeysUsersApiKeysGet(requestParameters: GetApiKeysUsersApiKeysGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeysResponse> {
        const response = await this.getApiKeysUsersApiKeysGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save Api Keys
     */
    async saveApiKeysUsersApiKeysPostRaw(requestParameters: SaveApiKeysUsersApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeysResponse>> {
        if (requestParameters['apiKeyPayload'] == null) {
            throw new runtime.RequiredError(
                'apiKeyPayload',
                'Required parameter "apiKeyPayload" was null or undefined when calling saveApiKeysUsersApiKeysPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skipRevokedCheck'] != null) {
            queryParameters['skip_revoked_check'] = requestParameters['skipRevokedCheck'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['x-device-id'] = String(requestParameters['xDeviceId']);
        }


        let urlPath = `/users/api-keys`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiKeyPayloadToJSON(requestParameters['apiKeyPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeysResponseFromJSON(jsonValue));
    }

    /**
     * Save Api Keys
     */
    async saveApiKeysUsersApiKeysPost(requestParameters: SaveApiKeysUsersApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeysResponse> {
        const response = await this.saveApiKeysUsersApiKeysPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
